# Generated by Django 4.2.4 on 2023-08-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='book_id',
            field=models.CharField(max_length=50),
        ),
    ]
