# Generated by Django 4.2.4 on 2023-08-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_dialog',
            field=models.CharField(max_length=1024),
        ),
    ]
