# Generated by Django 4.2.4 on 2023-08-04 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_chapter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.book'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_academyAwardNominations',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_academyAwardWins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_boxOfficeRevenueInMillions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_budgetInMillions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_rottenTomatoesScore',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_runtimeInMinutes',
            field=models.IntegerField(),
        ),
    ]
