# Generated by Django 4.2.4 on 2023-08-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_chapter_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_boxOfficeRevenueInMillions',
            field=models.FloatField(),
        ),
    ]
